DROP TABLE IF EXISTS DominionExpansion
DROP TABLE IF EXISTS [Card]
DROP TABLE IF EXISTS Cost

CREATE TABLE DominionExpansion(
[Id] INT NOT NULL IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL
)

ALTER TABLE DominionExpansion ADD CONSTRAINT PK_DominionExpansion PRIMARY KEY(Id)

CREATE TABLE Cost(
[Id] INT NOT NULL IDENTITY(1,1),
[Money] INT NULL,
[Potion] INT NULL,
[Dept] INT NULL
)

ALTER TABLE Cost ADD CONSTRAINT PK_Cost PRIMARY KEY(Id)

CREATE TABLE [CardType](
[Id] INT NOT NULL IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL
)

ALTER TABLE [CardType] ADD CONSTRAINT PK_Type PRIMARY KEY(Id)

CREATE TABLE [Card](
[Id] INT NOT NULL IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL,
[CostId] INT NOT NULL,
[DominionExpansionId] INT NOT NULL,
[CardTypeId] INT NOT NULL
)

ALTER TABLE [Card] ADD CONSTRAINT PK_Card PRIMARY KEY(Id)
ALTER TABLE [Card] ADD CONSTRAINT FK_Card_DominionExpansion FOREIGN KEY (DominionExpansionId) REFERENCES DominionExpansion(Id)
ALTER TABLE [Card] ADD CONSTRAINT FK_Card_Cost FOREIGN KEY (CostId) REFERENCES Cost(Id)
ALTER TABLE [Card] ADD CONSTRAINT FK_Card_CardType FOREIGN KEY (CardTypeId) REFERENCES [CardType](Id)
